### ISSUE TITLE
Bump to Scala 2.12.0

### ISSUE THREAD

**Issue by 3tty0n** [guidosalva/REScala#25]
We need:

- [x] scalatest https://github.com/scalatest/scalatest/issues/989
- [x] mockito https://github.com/mockito/mockito/pull/338
- [ ] junit-interface https://github.com/sbt/junit-interface/issues/75

**Comment by rmgk** [comment]
Hi, much of the development on REScala has happened in private over the last couple of years, but we have been working on publishing that code again. Your issue has pushed that process a bit, and I have pushed the updates to this repository.
We did remove the dependencies on mockito and junit, so the current snapshot does compile with scala 2.12.0. Feel free to test :-)
